src/Entity/Loan.php
<?php

namespace App\Entity;

use App\Validator\Constraints as AppAssert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LoanRepository")
 */
class Loan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="loans", fetch="EAGER", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank(message="Le livre est obligatoire")
     * @AppAssert\BookIsLoaned()
     */
    private $book;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="loans", fetch="EAGER", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank(message="L'utilisateur est obligatoire")
     */
    private $user;

    /**
     * @ORM\Column(type="date")
     */
    private $startDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $endDate;

    public function __construct()
    {
        $this->startDate = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function isReturned()
    {
        return !is_null($this->endDate);
    }

    /**
     * @return bool
     */
    public function isLate()
    {
        if (!$this->isReturned()) {
            $now = new \DateTime();

            return $now->sub(self::getReturnDelay()) > $this->startDate;
        }

        return false;
    }

    /**
     * @return \DateInterval
     */
    public static function getReturnDelay()
    {
        // interval d'un mois
        return new \DateInterval('P1M');
    }
}

src/Form/LoanType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\Loan;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LoanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'user',
                EntityType::class,
                [
                    'label' => 'Utilisateur',
                    'class' => User::class,
                    'placeholder' => 'Choisissez'
                ]
            )
            ->add(
                'book',
                EntityType::class,
                [
                    'label' => 'Livre',
                    'class' => Book::class,
                    'choice_label' => 'title',
                    'placeholder' => 'Choisissez'
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Loan::class,
        ]);
    }
}

src/Controller/LoanController.php
<?php

namespace App\Controller;

use App\Entity\Loan;
use App\Form\LoanType;
use App\Repository\LoanRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class LoanController
 * @package App\Controller
 *
 * @Route("/emprunts")
 */
class LoanController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function index(LoanRepository $loanRepository)
    {
        $loans = $loanRepository->findBy(
            [],
            ['startDate' => 'DESC']
        );

        return $this->render(
            'loan/index.html.twig',
            [
                'loans' => $loans
            ]
        );
    }

    /**
     * @Route("/nouveau")
     */
    public function add(Request $request, EntityManagerInterface $em)
    {
        $loan = new Loan();

        $form = $this->createForm(LoanType::class, $loan);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $em->persist($loan);
                $em->flush();

                $this->addFlash('success', "L'emprunt est enregistré");

                return $this->redirectToRoute('app_loan_index');
            } else {
                $this->addFlash('error', 'Le formulaire contient des erreurs');
            }
        }

        return $this->render(
            'loan/add.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * @Route("/retour/{id}")
     */
    public function registerReturn(EntityManagerInterface $em, Loan $loan)
    {
        $loan->setEndDate(new \DateTime());

        $em->flush();

        $this->addFlash('success', 'Le livre est rendu');

        return $this->redirectToRoute('app_loan_index');
    }
}

templates/loan/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel emprunt{% endblock %}

{% block body %}
    <h1>Nouvel emprunt</h1>

    {{ form_start(form) }}

    {{ form_row(form.user) }}
    {{ form_row(form.book) }}

    <div class="text-right">
        <button type="submit" class="btn btn-primary">
            Enregistrer
        </button>
        <a href="{{ path('app_loan_index') }}"
           class="btn btn-outline-secondary">
            Retour
        </a>
    </div>

    {{ form_end(form) }}
{% endblock %}

templates/loan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunts{% endblock %}

{% block body %}
    <h1>Gestion emprunts</h1>

    <a href="{{ path('app_loan_add') }}"
       class="btn btn-outline-primary mb-3">
        Nouvel Emprunt
    </a>

    <table class="table">
        <tr>
            <th>Utilisateur</th>
            <th>Livre</th>
            <th>Date sortie</th>
            <th>Date retour</th>
            <th width="150px"></th>
        </tr>
        {% for loan in loans %}
            <tr>
                <td>{{ loan.user }}</td>
                <td>{{ loan.book }}</td>
                <td>{{ loan.startDate|date('d/m/Y') }}</td>
                <td>
                    {% if loan.returned %}
                        {{ loan.endDate|date('d/m/Y') }}
                    {% else %}
                        En cours
                    {% endif %}
                </td>
                <td>
                    {% if not loan.returned %}
                        <a href="{{ path('app_loan_registerreturn', {'id': loan.id}) }}" class="btn btn-primary">
                            Retour
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}